/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz.vistas;

/**
 *
 * @author chiqu
 */
public class PanelDetallesPartida extends javax.swing.JPanel {

    /**
     * Creates new form PanelDetallesPartida
     */
    
    
    
    public PanelDetallesPartida() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFechaPartida = new javax.swing.JLabel();
        lblCantJugadores = new javax.swing.JLabel();
        lblTotalApostado = new javax.swing.JLabel();
        lblCantManosJugadas = new javax.swing.JLabel();

        lblFechaPartida.setText("fecha");

        lblCantJugadores.setText("cantJugadores");

        lblTotalApostado.setText("totalApostado");

        lblCantManosJugadas.setText("cantManosJugadas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFechaPartida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCantJugadores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTotalApostado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCantManosJugadas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaPartida)
                    .addComponent(lblCantJugadores)
                    .addComponent(lblTotalApostado)
                    .addComponent(lblCantManosJugadas))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel lblCantJugadores;
    public javax.swing.JLabel lblCantManosJugadas;
    public javax.swing.JLabel lblFechaPartida;
    public javax.swing.JLabel lblTotalApostado;
    // End of variables declaration//GEN-END:variables
}
