/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz.vistas;

/**
 *
 * @author chiqu
 */
public class PanelDetallesJugadores extends javax.swing.JPanel {

    /**
     * Creates new form PanelDetallesJugadores
     */
    public PanelDetallesJugadores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        lblTotalApostado = new javax.swing.JLabel();
        lblSaldoInicial = new javax.swing.JLabel();
        lblTotalGanado = new javax.swing.JLabel();

        lblNombre.setText("nombre");

        lblTotalApostado.setText("totalApostado");

        lblSaldoInicial.setText("saldoInicial");

        lblTotalGanado.setText("totalGanado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblNombre)
                .addGap(18, 18, 18)
                .addComponent(lblTotalApostado)
                .addGap(18, 18, 18)
                .addComponent(lblSaldoInicial)
                .addGap(18, 18, 18)
                .addComponent(lblTotalGanado)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(lblTotalApostado)
                    .addComponent(lblSaldoInicial)
                    .addComponent(lblTotalGanado))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel lblNombre;
    public javax.swing.JLabel lblSaldoInicial;
    public javax.swing.JLabel lblTotalApostado;
    public javax.swing.JLabel lblTotalGanado;
    // End of variables declaration//GEN-END:variables
}
