/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz.vistas;


import interfaz.IVistaAdmin;
import interfaz.controladores.ControladorAdmin;
import java.util.List;
import logica.Partida;
import logica.UsuarioAdministrador;

/**
 *
 * @author chiqu
 */
public class VistaAdministrador extends javax.swing.JFrame implements IVistaAdmin{

    private UsuarioAdministrador esteAdmin;
    private ControladorAdmin ca;
  
    /**
     * Creates new form VistaAdministrador
     */
    public VistaAdministrador(UsuarioAdministrador admin) {
         ca = new ControladorAdmin(this);
        
         this.esteAdmin = admin;
       
        initComponents();
        initListaYLabels();
         ca.actualizar();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listaPartidasEnCurso = new javax.swing.JList();
        labelPartidasEnCurso = new javax.swing.JLabel();
        labelDetallesPartida = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDetallesPartida = new javax.swing.JTextArea();
        labelAdminNick = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setViewportView(listaPartidasEnCurso);

        labelPartidasEnCurso.setText("Partidas en curso");

        labelDetallesPartida.setText("Detalles de la partida:");

        txtDetallesPartida.setColumns(20);
        txtDetallesPartida.setRows(5);
        jScrollPane2.setViewportView(txtDetallesPartida);

        labelAdminNick.setForeground(new java.awt.Color(255, 51, 51));
        labelAdminNick.setText("labelAdminNick");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelPartidasEnCurso))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelDetallesPartida)))
                    .addComponent(labelAdminNick))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelAdminNick)
                        .addGap(23, 23, 23)
                        .addComponent(labelPartidasEnCurso))
                    .addComponent(labelDetallesPartida, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelAdminNick;
    private javax.swing.JLabel labelDetallesPartida;
    private javax.swing.JLabel labelPartidasEnCurso;
    private javax.swing.JList listaPartidasEnCurso;
    private javax.swing.JTextArea txtDetallesPartida;
    // End of variables declaration//GEN-END:variables

    private void initListaYLabels() {
        labelAdminNick.setText("Bienvenido " + this.esteAdmin.getNombreCompleto() +  "!");
    }

    @Override
    public void actualizar(List<Partida> partidasEnCurso) {
        this.listaPartidasEnCurso.setListData(partidasEnCurso.toArray());
    }
}
